// generated from https://cdn.jsdelivr.net/npm/@fawazahmed0/currency-api@latest/v1/currencies.json
const currencyNames = {
    "1INCH": "1inch",
    "AAVE": "Aave",
    "ADA": "Cardano",
    "AED": "Emirati Dirham",
    "AFN": "Afghan Afghani",
    "AGIX": "SingularityNET",
    "AKT": "Akash Network",
    "ALGO": "Algorand",
    "ALL": "Albanian Lek",
    "AMD": "Armenian Dram",
    "AMP": "Amp",
    "ANG": "Dutch Guilder",
    "AOA": "Angolan Kwanza",
    "APE": "ApeCoin",
    "APT": "Aptos",
    "AR": "Arweave",
    "ARB": "Arbitrum",
    "ARS": "Argentine Peso",
    "ATOM": "Cosmos",
    "ATS": "Austrian Schilling",
    "AUD": "Australian Dollar",
    "AVAX": "Avalanche",
    "AWG": "Aruban or Dutch Guilder",
    "AXS": "Axie Infinity",
    "AZM": "Azerbaijani Manat",
    "AZN": "Azerbaijan Manat",
    "BAKE": "BakeryToken",
    "BAM": "Bosnian Convertible Mark",
    "BAT": "Basic Attention Token",
    "BBD": "Barbadian or Bajan Dollar",
    "BCH": "Bitcoin Cash",
    "BDT": "Bangladeshi Taka",
    "BEF": "Belgian Franc",
    "BGN": "Bulgarian Lev",
    "BHD": "Bahraini Dinar",
    "BIF": "Burundian Franc",
    "BMD": "Bermudian Dollar",
    "BNB": "Binance Coin",
    "BND": "Bruneian Dollar",
    "BOB": "Bolivian Bolíviano",
    "BRL": "Brazilian Real",
    "BSD": "Bahamian Dollar",
    "BSV": "Bitcoin SV",
    "BSW": "Biswap",
    "BTC": "Bitcoin",
    "BTCB": "Bitcoin BEP2",
    "BTG": "Bitcoin Gold",
    "BTN": "Bhutanese Ngultrum",
    "BTT": "BitTorrent",
    "BUSD": "Binance USD",
    "BWP": "Botswana Pula",
    "BYN": "Belarusian Ruble",
    "BYR": "Belarusian Ruble",
    "BZD": "Belizean Dollar",
    "CAD": "Canadian Dollar",
    "CAKE": "PancakeSwap",
    "CDF": "Congolese Franc",
    "CELO": "Celo",
    "CFX": "Conflux",
    "CHF": "Swiss Franc",
    "CHZ": "Chiliz",
    "CLP": "Chilean Peso",
    "CNH": "Chinese Yuan Renminbi Offshore",
    "CNY": "Chinese Yuan Renminbi",
    "COMP": "Compound",
    "COP": "Colombian Peso",
    "CRC": "Costa Rican Colon",
    "CRO": "Crypto.com Chain",
    "CRV": "Curve DAO Token",
    "CSPR": "Casper",
    "CUC": "Cuban Convertible Peso",
    "CUP": "Cuban Peso",
    "CVE": "Cape Verdean Escudo",
    "CVX": "Convex Finance",
    "CYP": "Cypriot Pound",
    "CZK": "Czech Koruna",
    "DAI": "DAI",
    "DASH": "Digital Cash",
    "DCR": "Decred",
    "DEM": "German Deutsche Mark",
    "DFI": "DfiStarter",
    "DJF": "Djiboutian Franc",
    "DKK": "Danish Krone",
    "DOGE": "Dogecoin",
    "DOP": "Dominican Peso",
    "DOT": "Polkadot",
    "DYDX": "dYdX",
    "DZD": "Algerian Dinar",
    "EEK": "Estonian Kroon",
    "EGLD": "Elrond",
    "EGP": "Egyptian Pound",
    "ENJ": "Enjin Coin",
    "EOS": "EOS",
    "ERN": "Eritrean Nakfa",
    "ESP": "Spanish Peseta",
    "ETB": "Ethiopian Birr",
    "ETC": "Ethereum Classic",
    "ETH": "Ethereum",
    "EUR": "Euro",
    "EURC": "Euro (Digital Currency)",
    "FEI": "Fei USD",
    "FIL": "Filecoin",
    "FIM": "Finnish Markka",
    "FJD": "Fijian Dollar",
    "FKP": "Falkland Island Pound",
    "FLOW": "Flow",
    "FLR": "FLARE",
    "FRAX": "Frax",
    "FRF": "French Franc",
    "FTT": "FarmaTrust",
    "GALA": "Gala",
    "GBP": "British Pound",
    "GEL": "Georgian Lari",
    "GGP": "Guernsey Pound",
    "GHC": "Ghanaian Cedi",
    "GHS": "Ghanaian Cedi",
    "GIP": "Gibraltar Pound",
    "GMD": "Gambian Dalasi",
    "GMX": "Goldmaxcoin",
    "GNF": "Guinean Franc",
    "GNO": "Gnosis",
    "GRD": "Greek Drachma",
    "GRT": "The Graph",
    "GT": "GateToken",
    "GTQ": "Guatemalan Quetzal",
    "GUSD": "Gemini US Dollar",
    "GYD": "Guyanese Dollar",
    "HBAR": "Hedera",
    "HKD": "Hong Kong Dollar",
    "HNL": "Honduran Lempira",
    "HNT": "Helium",
    "HOT": "Hydro Protocol",
    "HRK": "Croatian Kuna",
    "HT": "Huobi Token",
    "HTG": "Haitian Gourde",
    "HUF": "Hungarian Forint",
    "ICP": "Internet Computer",
    "IDR": "Indonesian Rupiah",
    "IEP": "Irish Pound",
    "ILS": "Israeli Shekel",
    "IMP": "Isle of Man Pound",
    "IMX": "Immutable X",
    "INJ": "Injective",
    "INR": "Indian Rupee",
    "IQD": "Iraqi Dinar",
    "IRR": "Iranian Rial",
    "ISK": "Icelandic Krona",
    "ITL": "Italian Lira",
    "JEP": "Jersey Pound",
    "JMD": "Jamaican Dollar",
    "JOD": "Jordanian Dinar",
    "JPY": "Japanese Yen",
    "KAS": "Kaspa",
    "KAVA": "Kava",
    "KCS": "Kucoin",
    "KDA": "Kadena",
    "KES": "Kenyan Shilling",
    "KGS": "Kyrgyzstani Som",
    "KHR": "Cambodian Riel",
    "KLAY": "Klaytn",
    "KMF": "Comorian Franc",
    "KNC": "Kyber Network Crystals",
    "KPW": "North Korean Won",
    "KRW": "South Korean Won",
    "KSM": "Kusama",
    "KWD": "Kuwaiti Dinar",
    "KYD": "Caymanian Dollar",
    "KZT": "Kazakhstani Tenge",
    "LAK": "Lao Kip",
    "LBP": "Lebanese Pound",
    "LDO": "Lido DAO Token",
    "LEO": "LEOcoin",
    "LINK": "Chainlink",
    "LKR": "Sri Lankan Rupee",
    "LRC": "Loopring",
    "LRD": "Liberian Dollar",
    "LSL": "Basotho Loti",
    "LTC": "Litecoin",
    "LTL": "Lithuanian Litas",
    "LUF": "Luxembourg Franc",
    "LUNA": "Terra",
    "LUNC": "Luna Classic",
    "LVL": "Latvian Lat",
    "LYD": "Libyan Dinar",
    "MAD": "Moroccan Dirham",
    "MANA": "Mana Coin Decentraland",
    "MBX": "MobieCoin",
    "MDL": "Moldovan Leu",
    "MGA": "Malagasy Ariary",
    "MGF": "Malagasy Franc",
    "MINA": "Mina",
    "MKD": "Macedonian Denar",
    "MKR": "Maker",
    "MMK": "Burmese Kyat",
    "MNT": "Mongolian Tughrik",
    "MOP": "Macau Pataca",
    "MRO": "Mauritanian Ouguiya",
    "MRU": "Mauritanian Ouguiya",
    "MTL": "Maltese Lira",
    "MUR": "Mauritian Rupee",
    "MVR": "Maldivian Rufiyaa",
    "MWK": "Malawian Kwacha",
    "MXN": "Mexican Peso",
    "MXV": "Mexican Unidad de Inversión (UDI)",
    "MYR": "Malaysian Ringgit",
    "MZM": "Mozambican Metical",
    "MZN": "Mozambican Metical",
    "NAD": "Namibian Dollar",
    "NEAR": "NEAR Protocol",
    "NEO": "NEO",
    "NEXO": "NEXO",
    "NFT": "NFT",
    "NGN": "Nigerian Naira",
    "NIO": "Nicaraguan Cordoba",
    "NLG": "Dutch Guilder",
    "NOK": "Norwegian Krone",
    "NPR": "Nepalese Rupee",
    "NZD": "New Zealand Dollar",
    "OKB": "Okex",
    "OMR": "Omani Rial",
    "ONE": "Menlo One",
    "OP": "Optimism",
    "ORDI": "ORDI (Ordinals / BRC-20)",
    "PAB": "Panamanian Balboa",
    "PAXG": "PAX Gold",
    "PEN": "Peruvian Sol",
    "PEPE": "Pepe Coin",
    "PGK": "Papua New Guinean Kina",
    "PHP": "Philippine Peso",
    "PKR": "Pakistani Rupee",
    "PLN": "Polish Zloty",
    "POL": "Proof Of Liquidity",
    "PTE": "Portuguese Escudo",
    "PYG": "Paraguayan Guarani",
    "QAR": "Qatari Riyal",
    "QNT": "Quant",
    "QTUM": "QTUM",
    "ROL": "Romanian Leu",
    "RON": "Romanian Leu",
    "RPL": "Rocket Pool",
    "RSD": "Serbian Dinar",
    "RUB": "Russian Ruble",
    "RUNE": "THORChain (ERC20)",
    "RVN": "Ravencoin",
    "RWF": "Rwandan Franc",
    "SAND": "The Sandbox",
    "SAR": "Saudi Arabian Riyal",
    "SBD": "Solomon Islander Dollar",
    "SCR": "Seychellois Rupee",
    "SDD": "Sudanese Dinar",
    "SDG": "Sudanese Pound",
    "SEK": "Swedish Krona",
    "SGD": "Singapore Dollar",
    "SHIB": "Shiba Inu",
    "SHP": "Saint Helenian Pound",
    "SIT": "Slovenian Tolar",
    "SKK": "Slovak Koruna",
    "SLE": "Sierra Leonean Leone",
    "SLL": "Sierra Leonean Leone",
    "SNX": "Synthetix Network",
    "SOL": "Solana",
    "SOS": "Somali Shilling",
    "SPL": "Seborgan Luigino",
    "SRD": "Surinamese Dollar",
    "SRG": "Surinamese Guilder",
    "STD": "Sao Tomean Dobra",
    "STN": "Sao Tomean Dobra",
    "STX": "Stacks",
    "SUI": "Sui",
    "SVC": "Salvadoran Colon",
    "SYP": "Syrian Pound",
    "SZL": "Swazi Lilangeni",
    "THB": "Thai Baht",
    "THETA": "Theta",
    "TJS": "Tajikistani Somoni",
    "TMM": "Turkmenistani Manat",
    "TMT": "Turkmenistani Manat",
    "TND": "Tunisian Dinar",
    "TON": "Tokamak Network",
    "TOP": "Tongan Pa'anga",
    "TRL": "Turkish Lira (old)",
    "TRX": "TRON",
    "TRY": "Turkish Lira",
    "TTD": "Trinidadian Dollar",
    "TUSD": "True USD",
    "TVD": "Tuvaluan Dollar",
    "TWD": "Taiwan New Dollar",
    "TWT": "Trust Wallet Token",
    "TZS": "Tanzanian Shilling",
    "UAH": "Ukrainian Hryvnia",
    "UGX": "Ugandan Shilling",
    "UNI": "Uniswap",
    "USD": "US Dollar",
    "USDC": "USDC",
    "USDD": "Decentralized USD",
    "USDP": "USDP Stablecoin",
    "USDT": "Tether",
    "UYU": "Uruguayan Peso",
    "UZS": "Uzbekistani Som",
    "VAL": "Vatican City Lira",
    "VEB": "Venezuelan Bolívar",
    "VED": "Venezuelan Bolívar Digital",
    "VEF": "Venezuelan Bolívar",
    "VES": "Venezuelan Bolívar",
    "VET": "Vechain",
    "VND": "Vietnamese Dong",
    "VUV": "Ni-Vanuatu Vatu",
    "WAVES": "Waves",
    "WEMIX": "WEMIX",
    "WOO": "WOO Network",
    "WST": "Samoan Tala",
    "XAF": "Central African CFA Franc BEAC",
    "XAG": "Silver Ounce",
    "XAU": "Gold Ounce",
    "XAUT": "Tether Gold",
    "XBT": "Bitcoin (XBT)",
    "XCD": "East Caribbean Dollar",
    "XCG": "Xchange",
    "XCH": "Chia",
    "XDC": "XDC Network",
    "XDR": "IMF Special Drawing Rights",
    "XEC": "Eternal Coin",
    "XEM": "NEM",
    "XLM": "Stellar Lumen",
    "XMR": "Monero",
    "XOF": "CFA Franc",
    "XPD": "Palladium Ounce",
    "XPF": "CFP Franc",
    "XPT": "Platinum Ounce",
    "XRP": "Ripple",
    "XTZ": "Tezos",
    "YER": "Yemeni Rial",
    "ZAR": "South African Rand",
    "ZEC": "ZCash",
    "ZIL": "Zilliqa",
    "ZMK": "Zambian Kwacha",
    "ZMW": "Zambian Kwacha",
    "ZWD": "Zimbabwean Dollar",
    "ZWG": "Zimbabwe Gold (ZiG)",
    "ZWL": "Zimbabwean Dollar",
};

export default currencyNames;
